### ISSUE TITLE
additional request-reply pair ICMP Extended Echo

### ISSUE THREAD

**Issue by duffy-ocraven** [corelight/pycommunityid#2]
At https://tools.ietf.org/html/rfc8335 an additional request-reply pair is documented. 
   ICMP field Type: Extended Echo Request.  The value for ICMPv4 is 42.  The value for ICMPv6 is 160
   ICMP field Type: Extended Echo Reply.  The value for ICMPv4 is 43.  The value for ICMPv6 is 161

Since that wasn’t in the version 1 table, hashes have been using the code octet instead of the request-response peer type value.

**Comment by ckreibich** [comment]
Thanks Duffy, good to know. I wouldn't be surprised if there are others lurking out there.

The current flow treatment is based on Zeek's handling of ICMP/ICMPv6. Adding this new pair just to the Python implementation would be dangerous, since the ID value would then differ just for this implementation whenever the return value come up. The whole ICMP scenario is a bit of a corner case, but this is a good one to add to the v2 pile, so if you'd like to create a ticket over at https://github.com/corelight/community-id-spec I'd be grateful. Otherwise I'll go ahead and do so in a little while. We could also add this to Zeek itself.

I'll close this one for now until a v2 becomes actionable.

**Comment by duffy-ocraven** [comment]
When thinking through the implications, I similarly reached the conclusion that doing this revs the version. But then I thought: "maybe they are looking for an excuse to go to v2, and I'll lob this soft pitch". I'll go put this a bit of a corner case, to add to the v2 pile, as a ticket over at https://github.com/corelight/community-id-spec, as you suggest.

**Comment by ckreibich** [comment]
Haha yes, excuses for a v2 are very welcome! There's only a small handful so far. :-)
